import { UserProfile } from "@/lib/store";

export function generateResumePDF(name: string, email: string, profile: UserProfile) {
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${name} — Resume</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <style>
      body { font-family: -apple-system, Arial, sans-serif; margin: 24px; color: #222; font-size: 11pt; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      h1 { font-size: 20pt; color: #002d62; margin: 0 0 2px; }
      h2 { font-size: 13pt; color: #002d62; border-bottom: 2px solid #c8a415; padding-bottom: 3px; margin: 18px 0 8px; }
      .sub { color: #555; font-size: 10pt; margin-bottom: 12px; }
      .row { display: flex; flex-wrap: wrap; gap: 24px; }
      .col { flex: 1 1 260px; }
      ul { margin: 4px 0; padding-left: 18px; }
      li { margin-bottom: 3px; font-size: 10pt; }
      .score { color: #c8a415; font-weight: bold; }
      .toolbar { position: fixed; top: 8px; right: 8px; background: #002d62; color: #fff; padding: 8px 14px; border-radius: 8px; font-size: 12pt; cursor: pointer; box-shadow: 0 2px 8px rgba(0,0,0,.2); }
      @media print { .toolbar { display: none; } body { margin: 20px; } }
    </style></head><body>
    <button class="toolbar" onclick="window.print()">🖨️ Print / Save as PDF</button>
    <h1>${name}</h1>
    <p class="sub">${email} • Class of ${profile.gradYear}${profile.isST ? " • S/T Program" : ""}</p>
    <div class="row">
      <div class="col">
        <h2>Academic Profile</h2>
        <ul>
          ${profile.major ? `<li><b>Intended Major:</b> ${profile.major}</li>` : ""}
          ${profile.gpa ? `<li><b>GPA:</b> ${profile.gpa}</li>` : ""}
          ${profile.sat && !profile.testOptional ? `<li><b>SAT:</b> ${profile.sat}</li>` : ""}
          ${profile.act && !profile.testOptional ? `<li><b>ACT:</b> ${profile.act}</li>` : ""}
          ${profile.testOptional ? `<li><b>Test Optional</b></li>` : ""}
          ${profile.serviceHours ? `<li><b>Service Hours:</b> ${profile.serviceHours}/24</li>` : ""}
        </ul>
        ${profile.aps.length > 0 ? `
        <h2>AP Courses${Object.keys(profile.apScores || {}).length > 0 ? " & Scores" : ""}</h2>
        <ul>${profile.aps.sort().map(ap => { const score = profile.apScores?.[ap]; return `<li>${ap}${score ? ` — <span class="score">${score}/5</span>` : ""}</li>`; }).join("")}</ul>` : ""}
      </div>
      <div class="col">
        ${profile.clubs.length > 0 ? `<h2>Clubs & Organizations</h2><ul>${profile.clubs.sort().map(c => `<li>${c}</li>`).join("")}</ul>` : ""}
        ${profile.sports && profile.sports.length > 0 ? `<h2>Sports</h2><ul>${profile.sports.sort().map(s => `<li>${s}</li>`).join("")}</ul>` : ""}
      </div>
    </div>
    ${profile.extracurriculars.length > 0 ? `<h2>Extracurricular Activities</h2><ul>${profile.extracurriculars.map(e => `<li>${e}</li>`).join("")}</ul>` : ""}
    ${profile.achievements.length > 0 ? `<h2>Achievements & Awards</h2><ul>${profile.achievements.map(a => `<li>${a}</li>`).join("")}</ul>` : ""}
    <p style="text-align:center;color:#999;font-size:8pt;margin-top:30px;">Generated by RaidersMatch • Eleanor Roosevelt High School</p>
    <script>
      // Auto-trigger print on desktop; on iOS Safari the user taps the toolbar button
      // (iframe + window.print breaks on certain iPhones — this opens a real tab instead).
      var isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);
      if (!isIOS) { setTimeout(function(){ window.print(); }, 400); }
    </script>
  </body></html>`;

  const w = window.open("", "_blank");
  if (!w) {
    // Popup blocked — fall back to data URL navigation
    const url = "data:text/html;charset=utf-8," + encodeURIComponent(html);
    window.location.href = url;
    return;
  }
  w.document.open();
  w.document.write(html);
  w.document.close();
}
