import { UserProfile } from "@/lib/store";

export function generateResumePDF(name: string, email: string, profile: UserProfile) {
  const doc = document.createElement("iframe");
  doc.style.display = "none";
  document.body.appendChild(doc);
  const w = doc.contentWindow!;
  const d = w.document;

  d.open();
  d.write(`<!DOCTYPE html><html><head><style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #222; font-size: 11pt; }
    h1 { font-size: 20pt; color: #002d62; margin-bottom: 2px; }
    h2 { font-size: 13pt; color: #002d62; border-bottom: 2px solid #c8a415; padding-bottom: 3px; margin-top: 18px; margin-bottom: 8px; }
    .sub { color: #555; font-size: 10pt; margin-bottom: 12px; }
    .row { display: flex; gap: 30px; }
    .col { flex: 1; }
    ul { margin: 4px 0; padding-left: 18px; }
    li { margin-bottom: 3px; font-size: 10pt; }
    .score { color: #c8a415; font-weight: bold; }
    @media print { body { margin: 20px; } }
  </style></head><body>
    <h1>${name}</h1>
    <p class="sub">${email} • Class of ${profile.gradYear}${profile.isST ? " • S/T Program" : ""}</p>
    
    <div class="row">
      <div class="col">
        <h2>Academic Profile</h2>
        <ul>
          ${profile.major ? `<li><b>Intended Major:</b> ${profile.major}</li>` : ""}
          ${profile.gpa ? `<li><b>GPA:</b> ${profile.gpa}</li>` : ""}
          ${profile.sat && !profile.testOptional ? `<li><b>SAT:</b> ${profile.sat}</li>` : ""}
          ${profile.act && !profile.testOptional ? `<li><b>ACT:</b> ${profile.act}</li>` : ""}
          ${profile.testOptional ? `<li><b>Test Optional</b></li>` : ""}
          ${profile.serviceHours ? `<li><b>Service Hours:</b> ${profile.serviceHours}/24</li>` : ""}
        </ul>

        ${profile.aps.length > 0 ? `
        <h2>AP Courses${Object.keys(profile.apScores || {}).length > 0 ? " & Scores" : ""}</h2>
        <ul>
          ${profile.aps.sort().map(ap => {
            const score = profile.apScores?.[ap];
            return `<li>${ap}${score ? ` — <span class="score">${score}/5</span>` : ""}</li>`;
          }).join("")}
        </ul>` : ""}
      </div>
      <div class="col">
        ${profile.clubs.length > 0 ? `
        <h2>Clubs & Organizations</h2>
        <ul>${profile.clubs.sort().map(c => `<li>${c}</li>`).join("")}</ul>` : ""}

        ${profile.sports && profile.sports.length > 0 ? `
        <h2>Sports</h2>
        <ul>${profile.sports.sort().map(s => `<li>${s}</li>`).join("")}</ul>` : ""}
      </div>
    </div>

    ${profile.extracurriculars.length > 0 ? `
    <h2>Extracurricular Activities</h2>
    <ul>${profile.extracurriculars.map(e => `<li>${e}</li>`).join("")}</ul>` : ""}

    ${profile.achievements.length > 0 ? `
    <h2>Achievements & Awards</h2>
    <ul>${profile.achievements.map(a => `<li>${a}</li>`).join("")}</ul>` : ""}

    <p style="text-align:center;color:#999;font-size:8pt;margin-top:30px;">Generated by RaidersMatch • Eleanor Roosevelt High School</p>
  </body></html>`);
  d.close();

  setTimeout(() => {
    w.print();
    setTimeout(() => document.body.removeChild(doc), 1000);
  }, 500);
}
